server:
  servlet:
    contextPath: /account
  port: 9092
  tomcat:
    max-threads: 5

spring: 
  application:
    name: account
  data:
    mongodb:
      host: mongodb-server
      port: 27017
      database: account

eureka:
 client:
   service-url:
     defaultZone: http://eureka-server:8761/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics

logging:
  file:  
    name: ${logging.file.path}\account.log
    path: C:\Users\jmagalmo\Documents\proyectos\bootCamp-microservice\Log
  level:
    root: info
  pattern:
    file: '%d{HH:mm:ss.SSS} - %5p | ms-Account= [%12(ID: %8mdc{id})] [%21.21thread] | %-45.45logger{45} :  %msg%n'
    console: '%d{HH:mm:ss.SSS} - %highlight(%5p) | %green(ms-Account =) [%12(ID: %8mdc{id})] [%21.21thread] | %cyan(%-45.45logger{45}) :  %msg%n'
