server:
  port: 7001

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account
          uri: https://msaccount-jabmm.azurewebsites.net
          predicates:
            - Path=/account/**
        - id: account
          uri: https://msbootcoin-jabmm.azurewebsites.net
          predicates:
            - Path=/bootcoin/**
            
eureka:
  client:
    serviceUrl:
      defaultZone : https://eurekaserver-jhoss.azurewebsites.net/eureka