server:
  servlet:
    contextPath: /bootcoin
  port: 9097
  tomcat:
    max-threads: 5

spring: 
  application:
    name: bootcoin
  data:
    mongodb:
      uri: mongodb://mongdb-jhoss:EHUd25BRylFY4zBBrtoJviTxdoHVo9gR2XUHj1dcfpPEUc6JebagmhVkTh8TisXKM4StM6xgMwfNpyDa0ajdng==@mongdb-jhoss.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@mongdb-jhoss@
      database: bootcoin

eureka:
 client:
   service-url:
     defaultZone: https://eurekaserver-jhoss.azurewebsites.net/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics     
 
