server:
  servlet:
    contextPath: /transaction
  port: 9094
  tomcat:
    max-threads: 5

spring: 
  application:
    name: transaction
  data:
    mongodb:
      host: localhost
      port: 27017
      database: transactions

eureka:
 client:
   service-url:
     defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics
